name: Deploy Pixel Pantry to Server

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy Website Files
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Sync Files via SFTP
        uses: easingthemes/ssh-deploy@v5.1.0
        with:
          REMOTE_HOST: ${{ secrets.FTP_SERVER_HOST }}
          REMOTE_USER: ${{ secrets.FTP_USERNAME }}
          REMOTE_PORT: 22
          PASSWORD: ${{ secrets.FTP_PASSWORD }}
          TARGET: '/home/2511622/public_html/'
          SOURCE: '.'
          ARGS: '-rltgoD --delete'
